### ISSUE TITLE
Issues cloning on Windows

### ISSUE THREAD

**Issue by ian4uh** [nicolevanderhoeven/xios-guide-to-monsters#1]
There's one file that isn't  able to be cloned due to having a ':' in the filename similar to the Source Column.

In the CSV it's listed on line 1595:

- Name: Mador KhWayfinder's Guide to Eberron: Priest of Set

Error received in Github Desktop: 

```text
Cloning into 'C:\....\xios-guide-to-monsters'...
remote: Enumerating objects: 3926, done.        
remote: Counting objects: 100% (3926/3926), done.        
remote: Compressing objects: 100% (2755/2755), done.        
remote: Total 3926 (delta 1244), reused 3848 (delta 1169), pack-reused 0        
Receiving objects: 100% (3926/3926), 754.46 KiB | 1.05 MiB/s, done.
Resolving deltas: 100% (1244/1244), done.
error: invalid path 'monsterfiles/Mador KhWayfinder's Guide to Eberron: Priest of Set.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'


Would you like to retry cloning ?
```

Updated to remove 1 reference to Tome of Beasts: 331 that was already fixed in a newer version of the Repository.

**Comment by nicolevanderhoeven** [comment]
Hey, thanks! Yes, I found it myself as well - not sure how that happened - and fixed it. Thanks for pointing it out, though!

**Comment by ian4uh** [comment]
Thanks, I noticed the Tome of Beasts one was corrected, but I'm still getting this error when cloning using Github Desktop windows. Just tried it again now:

![image](https://user-images.githubusercontent.com/13475748/148680863-5f21599e-f366-41c9-bace-dc880d5ba9a6.png)
