### ISSUE TITLE
Out of order quotes

### ISSUE THREAD

**Issue by brandonbarringer** [nicolevanderhoeven/xios-guide-to-monsters#4]
Thanks for this resource. There a quite a few issues with quotes on some of the source URLs. I went ahead and fixed those in the attached file. I didn't have time for a pull request. 
[monsters.csv](https://github.com/nicolevanderhoeven/xios-guide-to-monsters/files/10891442/monsters.csv)

**Comment by nicolevanderhoeven** [comment]
Thanks, fixed now!
